# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 9000, host:9000
  config.vm.provider "virtualbox" do |vb|
     vb.name = "SciGraph Example Box"
     vb.memory = "2048"
  end
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y maven git openjdk-7-jdk xvfb
     echo "export DISPLAY=localhost:99" >> /home/vagrant/.profile
     Xvfb :99 &
  SHELL
end
